name: Sync Bank List and Database

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Sync Bank List
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Sync gem
        run: |
          bundle install
          bundle exec rake bsb:sync
          bundle exec rake bsb:version_update
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Extract git commit data
        uses: rlespinasse/git-commit-data-action@v1
      - name: Update Author info
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR
      - name: Raise PR
        id: demo-1
        uses: peter-evans/create-pull-request@v4
        with:
          branch: "update/auto-bank-list"
          base: master
          title: "Github Action updated ${{ steps.date.outputs.date }}"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          token: ${{ secrets.AUTO_SYNC_BANK_BOT }}
          delete-branch: true
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{steps.demo-1.outputs.pull-request-number }}
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{steps.demo-1.outputs.pull-request-number }}
          method: squash
