name: Update BSB Database

on:
  schedule:
    # https://crontab.guru/every-month
    # At 00:00 on day-of-month 1.
    - cron: "0 0 1 * *" 
  workflow_dispatch:

jobs:
  build:
    name: Update BSB Database & Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Update BSB Database & Version
        run: |
          bundle install
          bundle exec rake bsb:sync
          bundle exec rake && bundle exec rake bsb:version_update
      - id: get-date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: peter-evans/create-pull-request@v4
        id: raise-pr
        with:
          branch: "bot/${{ steps.get-date.outputs.date }}"
          base: master
          title: "${{ steps.get-date.outputs.date }} - periodic update of config/*.json database files."
          committer: GitHub Actions <actions@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          delete-branch: true
          # token: ${{ secrets.BSB_BOT_TOKEN }}
      - uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{steps.raise-pr.outputs.pull-request-number }}
      - uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{steps.raise-pr.outputs.pull-request-number }}
          method: squash
