name: Update BSB Database

on:
  schedule:
    # https://crontab.guru/every-month
    # At 00:00 on day-of-month 1.
    - cron: "0 0 1 * *" 
  workflow_dispatch:

jobs:
  build:
    name: Update BSB Database & Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Update BSB Database & Version
        run: |
          bundle install
          bundle exec rake bsb:sync
          bundle exec rake && bundle exec rake bsb:version_update
      - uses: EndBug/add-and-commit@v9
        with:
          message: periodic update of config/*.json database files.
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: 'config/*.json lib/bsb/.current-version'
